### ISSUE TITLE
I bequeath to you the pony of progress 

### ISSUE THREAD

**Issue by gbmhunter** [gsmecher/minimax#3]
![image](https://user-images.githubusercontent.com/2396869/199673702-682cfa64-70ac-4fda-ac03-b43e04c0be7e.png)

Hope you get the reference! :-)

**Comment by gsmecher** [comment]
I accept with reluctance and honour. Thanks, Geoffrey - happy to hear from you.

**Comment by gbmhunter** [comment]
Haha hope things are going well. And nice repo btw :-)
